language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

before_script:
    - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - cp .env.travis .env
    - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then travis_retry composer update --no-interaction --prefer-stable --no-suggest --ignore-platform-reqs; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then travis_retry composer update --no-interaction --prefer-stable --no-suggest; fi
    - ./artisan migrate --seed
    - mkdir ./tests/_output

script:
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 8.0

addons:
  artifacts:
    paths:
      - ./tests/_output
      - ./storage/logs
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_PHP_VERSION
    working_dir: WORKING_DIR
    bucket: travistests
    s3_region: us-east-1
